### ISSUE TITLE
Remove the redundant code in the profile.html

### ISSUE THREAD

**Issue by Shenr0n** [Shenr0n/Hacktober-webpage#9]
Some code in profile.html is redundant and the webpage looks weird. Resolve the issues in profile.html

**Comment by iGeekuPlay** [comment]
You need to allow branches so we can submit a Pull Request.

**Comment by iGeekuPlay** [comment]
<img width="1465" alt="screen shot 2018-10-09 at 11 09 01 pm" src="https://user-images.githubusercontent.com/20030644/46711016-72141400-cc18-11e8-878f-e6c5955a845c.png">

**Comment by Shenr0n** [comment]
@iGeekuPlay What do you mean by "I need to allow branches so people can PR" Can you explain more about it to me please. I haven't used it before and I'm unaware of what I am supposed to do
